### ISSUE TITLE
ASTRA runtime constraint

### ISSUE THREAD

**Issue by carterbox** [conda-forge/tomopy-feedstock#32]
Note to self. Add the following runtime constraint before merging the patch from tomopy/tomopy#457

```yaml
requirements:
  run_constrained:
    - astra-toolbox >1.8
```
